compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
mixed_precision: bf16         
num_processes: 4
gpu_ids: 0,1,2,3
machine_rank: 0
num_machines: 1

deepspeed_config:
  zero_stage: 2
  gradient_accumulation_steps: 1
  offload_param: false
  zero3_init_flag: false
  gradient_clipping: 1.0
